import type { IStore } from "../../store/types";

export const INITIAL_STORE_STATE: IStore = {
  lists: [
    {
      id: "9899fe3f-8fd9-400e-a067-8ef1ca2a5e69",
      name: "[HOW TO]",
      description: "A guide on how to use KLYX effectively.",
      currentItem: null,
      items: [
        {
          id: "55ba641c-7f33-47ef-944f-27ce4a6ed487",
          name: " Explore the List Page",
          description:
            'Take a moment to click the arrow icon (if available) to expand the description for each list. (Note: There won\'t be an arrow on the task page, so don\'t worry about searching for it 😉).\n\nThe list page is where you\'ll manage your tasks and lists efficiently. Let\'s familiarize ourselves with this essential section. \nTo manage a specific list, locate the three dots menu icon to the right of the list\'s name.\nTry out these actions:\n"Sort List": Experiment with sorting the tasks within the list to suit your preference.\n"Reset All Tasks": Reset the completion status of all tasks in the list.\n"Edit List": Explore how to modify the name and description of the list.\n"Delete List": Practice deleting a list (be careful, as this action is irreversible).\n\nOnce you feel comfortable exploring the list page, you can either click the "Play" button to start working on your tasks or click an arrow (if you\'re already on a task page) to proceed.',
          completed: false,
          counterLimit: null,
          counterAutoswitch: true,
          counterProgress: null,
          counterType: "none",
          timerSeconds: null,
          timerProgress: null,
          timerAutoswitch: true,
          timerAutostart: false,
        },
        {
          id: "a4cb8936-1da0-49b3-92fc-46c0551bf614",
          name: "Explore Timer Functionality",
          description:
            'In this task, you\'ll learn about the timer functionality within the app, including how to start it automatically and manually, and how task progression works when the timer completes.\n\nObserve that the timer starts manually by default. You can start it by clicking the "Start Timer" button.\nTo automatically start the timer when entering the task page, locate the setting at the bottom of the task page.\nExperiment with both timer start options to understand how they work.\nOnce the timer completes, the task will be marked as done, and you will be moved to the next task in your list.\nIf you prefer to stay on the completed task and not move automatically to the next one, find and uncheck the setting at the bottom of the task page.',
          completed: false,
          counterLimit: null,
          counterAutoswitch: true,
          counterProgress: null,
          counterType: "none",
          timerSeconds: "80",
          timerProgress: 0,
          timerAutoswitch: true,
          timerAutostart: false,
        },
        {
          id: "692168ff-9161-4e39-a88c-f6d89b765125",
          name: "Click me",
          description:
            'If you are on the list page, when you click on the task name it will start playing tasks from the task that was clicked on.\nNo need to click the name if you are in the task view already 😉.\n\nThis timer is automatically started. \nYou can:\nPause the timer by clicking the "Pause timer" button.\nReset the timer by clicking the "Reset timer" button.\n\nNote that the timer\'s progress is saved when you leave the page, allowing you to return later and continue where you left off.\n\nTo prevent your device\'s screen from turning off during long timers, check the "Keep screen awake" checkbox at the top of the page.\n\nExperiment with starting, pausing, resetting the timer, and enabling the screen awake feature. Once you\'re comfortable with these actions, proceed to the next task.',
          completed: false,
          counterLimit: null,
          counterAutoswitch: true,
          counterProgress: null,
          counterType: "none",
          timerSeconds: "60",
          timerProgress: 21,
          timerAutoswitch: false,
          timerAutostart: true,
        },
        {
          id: "b1918b18-98c6-471b-9874-64cbba4271e6",
          name: "Understanding Limited Counters",
          description:
            "In this task, you'll learn how to work with a limited counter, which is ideal for tasks that need to be repeated a specific number of times, like tongue twisters or push-ups.\n\nYou'll notice a counter on the task page, displaying the current count.\n\nBy default, when the counter reaches the limit, the app will automatically move you to the next task in your list.\nIf you prefer not to move automatically to the next task upon reaching the limit, find and uncheck the setting at the bottom of the task page.\nPractice using the limited counter feature by incrementing the count to reach the specified limit. Once you're comfortable, you can proceed to the next task.\n\nClick the \"+ button\" next to the counter to increase the count. Continue doing so until you reach the predefined limit (e.g., 10).",
          completed: false,
          counterLimit: "10",
          counterAutoswitch: true,
          counterProgress: 0,
          counterType: "limited",
          timerSeconds: null,
          timerProgress: null,
          timerAutoswitch: true,
          timerAutostart: false,
        },
        {
          id: "f6e3e99f-7178-4e72-a79a-9ba2eb092f6b",
          name: "Understanding Unlimited Counters",
          description:
            "In this task, you'll explore the use of an unlimited counter, which allows you to repeat a task as many times as needed without a predefined limit.\n\nYou'll notice a counter on the task page, displaying the current count.\nClick the \"+ button\" next to the counter to increase the count. You can keep increasing it without any predefined limit (How high can it go? 🤷).\n\nUnlike limited counters, unlimited counters don't have a maximum count, so you can continue repeating the task as many times as you wish.\n\nOnce you're satisfied with the number of repetitions, click the arrow icon with a checked checkbox to mark the task as completed and proceed to the next one.",
          completed: false,
          counterLimit: null,
          counterAutoswitch: true,
          counterProgress: 0,
          counterType: "unlimited",
          timerSeconds: null,
          timerProgress: 0,
          timerAutoswitch: true,
          timerAutostart: false,
        },
        {
          id: "257e5efc-8ea2-4c4d-a816-0ee3789dfb88",
          name: "<- Click this check box",
          description:
            "To the right of the task's name, you'll see a checkbox. Click the checkbox to toggle the task's completion state.\n\nIn this task, you'll learn how to toggle the completion state of tasks, and you'll discover the impact on limited counters and timers.\n\nObserve that when you mark a completed task as incomplete, it will reset the counter and timer progress.\nWhen you mark an incomplete task as completed, it will update limited counter and timer to their completed progress state.\n\nTry toggling the task's completion state back and forth to understand how it affects counters and timers.\n\nOnce you're familiar with this feature, click the arrow icon in the middle (the one with an unchecked checkbox) to move to the next task without changing the completion state.",
          completed: false,
          counterLimit: "4",
          counterAutoswitch: false,
          counterProgress: null,
          counterType: "limited",
          timerSeconds: "300",
          timerProgress: null,
          timerAutoswitch: false,
          timerAutostart: false,
        },
        {
          id: "f270564b-ca15-47fb-93e1-3f5221b7b605",
          name: "Choose a Theme Color",
          description:
            'Personalize your app experience by selecting a theme color for the interface. You can experiment with different colors to find the one that suits your preferences best.\n\n1. Tap the gear icon located at the top right corner of the page to access the settings menu.\n2. Within the settings, find the "Choose theme color" option in the "Theme" section.\n3. Choose your first preferred color and apply it.\n4. After applying the color, take a moment to explore the app with the new theme.\n5. Repeat this process three more times, selecting different colors each time to see which one you like the most.\n\nExperiment with different colors to find the one that provides the best visual experience and suits your taste.',
          completed: true,
          counterLimit: "4",
          counterAutoswitch: true,
          counterProgress: 4,
          counterType: "limited",
          timerSeconds: null,
          timerProgress: null,
          timerAutoswitch: true,
          timerAutostart: false,
        },
        {
          id: "13ca4a21-cf94-486f-b149-2b3c6c926f13",
          name: "Backup and Restore",
          description:
            'Learn how to back up and restore the current state of the app, including all your progress. This feature is essential for safeguarding your data and tasks.\n\n\nBefore You Start: Ensure you have a list named "Delete me" on the home page. If not, create a new list to serve as a reference point.\n\n1. Click on the gear icon located at the top of the screen to access the app\'s settings.\n2. In the settings menu, locate and click on the "Download Backup of Your Data" button. This action will create a backup of your current app state, preserving your tasks and progress.\n3. To experience the restoration process, return to the home page by clicking the logo in the left corner of the page, and delete a list with the name "Delete me".\n4. Open the downloaded backup file and copy its contents.\n5. Navigate to the "Restore" section within the settings page.\n6. Paste the copied contents from the backup file into the provided text area for restoration.\n7. Click the "Restore" button to initiate the restoration process.\n8. Return to the home page and observe that the previously deleted list, "Delete me," has been successfully restored.\n9. If you change your mind and decide not to keep the restored state, you can use the "Swap Back" feature.\n10. Head to the settings page and locate the "Swap Back" button.\n11. Click on the "Swap Back" button.\n12. Return to the home page and notice that the restored list is no longer present. The app has reverted to the state it was in just before the restoration.\n13. Keep in mind that you can swap between two states as often as you like, but remember that when you restore a state, the state that is not currently active will be replaced by the current active state.\n',
          completed: false,
          counterLimit: null,
          counterAutoswitch: true,
          counterProgress: null,
          counterType: "none",
          timerSeconds: null,
          timerProgress: null,
          timerAutoswitch: true,
          timerAutostart: false,
        },
      ],
    },
    {
      id: "8c51bacf-6084-4427-828f-a1cea3f867bc",
      name: "Delete me",
      description: "Don't delete me just yet. You will know when.",
      currentItem: null,
      items: [],
    },
  ],
};
